name: moodiary
description: "A fully open source cross-platform diary app written by flutter and rust."
publish_to: 'none'
version: 2.7.1+71

environment:
  sdk: '>=3.6.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

  refreshed: 2.10.4
  dio: 5.7.0
  path: 1.9.0
  path_provider: 2.1.5
  calendar_date_picker2: 1.1.8
  logger: 2.5.0
  flutter_drawing_board: 0.9.5
  flutter_displaymode: 0.6.0
  fl_chart: 0.70.2
  file_picker: 8.1.7
  local_auth: 2.3.0
  local_auth_android: 1.0.46
  permission_handler: 11.3.1
  image_picker: 1.1.2
  device_info_plus: 11.2.1
  photo_view: 0.15.0
  package_info_plus: 8.1.3
  uuid: 4.5.1
  flutter_quill: 11.0.0-dev.21
  share_plus: 10.1.4
  url_launcher: 6.3.1
  archive: 4.0.2
  crypto: 3.0.6
  markdown_widget: 2.3.2+6
  flutter_colorpicker: 1.1.0
  geolocator: 13.0.2
  shared_preferences: 2.3.5
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  fluttertoast: 8.2.10
  cached_network_image: 3.4.1
  audioplayers: 6.1.0
  record: 5.2.0
  duration: 4.0.3
  dynamic_color: 1.7.0
  supabase_flutter: 2.8.3
  bitsdojo_window: 0.1.6
  intl: 0.19.0
  collection: 1.19.0
  cupertino_icons: 1.0.8
  font_awesome_flutter: 10.8.0
  tflite_flutter: 0.11.0
  sliver_tools: 0.2.12
  lottie: 3.3.1
  media_kit: 1.1.11
  media_kit_video: 1.2.5
  media_kit_libs_video: 1.0.5
  flutter_adaptive_scaffold: 0.3.1
  cross_file: 0.3.4+2
  fc_native_video_thumbnail: 0.17.2
  flutter_map: 7.0.2
  flutter_map_tile_caching: 10.0.0
  flutter_map_marker_cluster: 1.4.0
  latlong2: 0.9.1
  shelf: 1.4.2
  shelf_multipart: 2.0.0
  waterfall_flow: 3.1.0
  smooth_page_indicator: 1.2.0+3
  unicons: 3.0.0
  encrypt: 5.0.3
  objectbox: 4.0.3
  faker: 2.2.0
  flutter_rust_bridge: 2.7.0
  syncfusion_flutter_sliders: 28.1.41
  flutter_quill_extensions: 11.0.0-dev.7
  connectivity_plus: 6.1.2
  image_picker_android: 0.8.12+20
  video_player_media_kit: 1.0.5
  video_player: 2.9.2
  chewie: 1.9.2
  flutter_markdown: 0.7.5
  image_picker_platform_interface: 2.10.1
  chinese_font_library: 1.2.0
  flutter_image_compress: 2.4.0
  mime: 1.0.6
  auto_size_text_field: 2.2.4
  webdav_client: 1.2.2
  confetti: 0.8.0
  flutter_native_splash: 2.4.4
  gal: 2.3.1
  rive_animated_icon:
    git:
      url: https://github.com/ZhuJHua/rive_animated_icons.git
      ref: feature/add-new-component
  network_info_plus: 6.1.3
  scrollable_positioned_list: 0.3.8
  flutter_localizations:
    sdk: flutter
  rust_lib_mood_diary:
    path: rust_builder
  slang: 4.4.1
  slang_flutter: 4.4.0
  modal_bottom_sheet: 3.0.0
  sheet: 1.0.0
  tutorial_coach_mark: 1.2.12
  adaptive_dialog: 2.4.0
  flutter_inappwebview: 6.1.5
  sensors_plus: 6.1.1
  markdown: 7.3.0


dev_dependencies:
  #  flutter_test:
  #    sdk: flutter
  build_runner: 2.4.14
  flutter_launcher_icons: 0.14.3
  slang_build_runner: 4.4.0
  msix: 3.16.8
  flutter_lints: 5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/light/light_foreground.png"
  adaptive_icon_monochrome: "assets/icon/light/light_foreground.png"
  image_path_ios_dark_transparent: "assets/icon/dark/dark_foreground.png"
  image_path_ios_tinted_grayscale: "assets/icon/light/light_foreground.png"
  desaturate_tinted_to_grayscale_ios: true
  image_path: "assets/icon/light/light_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 26
  windows:
    generate: true
    image_path: "assets/icon/light/light_icon_desktop.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/light/light_icon_desktop.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/light/light_splash_icon.png
  color_dark: "#000000"
  image_dark: assets/icon/dark/dark_splash_icon.png

  android_12:
    image: assets/icon/light/light_splash_icon.png
    color: "#ffffff"
    image_dark: assets/icon/dark/dark_splash_icon.png
    color_dark: "#000000"
  fullscreen: true
  web: false

flutter:
  generate: true
  fonts:
    - family: qweather
      fonts:
        - asset: assets/fonts/qweather-icons.ttf

  assets:
    - assets/icon/dark/
    - assets/icon/light/
    - assets/lottie/
    - res/sponsor/

  uses-material-design: true

msix_config:
  display_name: Moodiary
  publisher_display_name: <PublisherName>
  identity_name: <PublisherName.AppName>
  publisher: <PublisherID>
  msix_version: 1.0.0.0
  logo_path: ./logo/<file_name.png>
  store: true
